LIBC_OBJ += $(SRC_PATH)/string/memcpy.o \
			$(SRC_PATH)/string/memset.o \
 			$(SRC_PATH)/string/strcpy.o \
			$(SRC_PATH)/string/strncpy.o \
			$(SRC_PATH)/string/strdup.o \
			$(SRC_PATH)/string/strndup.o \
			$(SRC_PATH)/string/strcat.o \
			$(SRC_PATH)/string/strncat.o \
			$(SRC_PATH)/string/strlen.o \
			$(SRC_PATH)/string/strtok.o \
			$(SRC_PATH)/string/strcmp.o \
			$(SRC_PATH)/string/strncmp.o


