LIBC_OBJ += $(SRC_PATH)/stdio/fprintf.o \
            $(SRC_PATH)/stdio/printf_common.o \
            $(SRC_PATH)/stdio/printf.o \
            $(SRC_PATH)/stdio/sprintf.o \
            $(SRC_PATH)/stdio/snprintf.o \
            $(SRC_PATH)/stdio/stdio.o \
            $(SRC_PATH)/stdio/vfprintf.o \
            $(SRC_PATH)/stdio/vsprintf.o \
            $(SRC_PATH)/stdio/vsnprintf.o \
            $(SRC_PATH)/stdio/vprintf.o

